name: mobile_stack
version: 0.8.46+202
mobilestack_work: 364
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: 2.1.3
  crypto: ^3.0.6
  file_picker: ^8.1.7
  path: ^1.9.0
  path_provider: ^2.1.6
  share_plus: ^12.0.2
  workmanager: ^0.10.7
  flutter_local_notifications: ^22.2.0
  image: ^4.9.2
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences_platform_interface: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/mobile_stack_brand.png
    - assets/images/mobile_stack_icon_source.png
